export type WorkReport = {
  id: string;
  folio: string;
  subsistema: string;
  ubicacion: string;
  fechaHoraInicio: string;
  turno: string;
  frecuencia: string;
  tipoMantenimiento: string;
  trabajadores: string[];
  inspeccionRealizada: boolean;
  observacionesActividad?: string;
  evidencias?: string[];
  herramientas?: string[];
  refacciones?: string[];
  observacionesGenerales?: string;
  nombreResponsable: string;
  fechaHoraTermino: string;
  firmaResponsable?: string | null;
};
